name: git_baseline1
DB: /DB/TAU-urban-acoustic-scenes-2019-development/
meta_scp: meta.csv
fold_scp: evaluation_setup/fold1_train.csv
wav_dir: wave_np/
gpu_idx: [0] #[0, 1]
nb_proc_db: 4
save_dir: /exp/DNNs/
optimizer: Adam #sgd
lr: 0.0001
opt_mom: 0.9
wd: 0.001
epoch: 90
batch_size: 24 #50 #24
#nb_samp: 479520
nb_samp: 240000
c_loss_weight: 0.00005
c_loss_lr: 0.5
#lrdec_milestones: [20, 50]
#lrdec: 0.2
mixup_start: 5
mixup_alpha: 0.1
dir_label_dic: label_dic.pk

#flags
comet_disable: 0
nesterov: 0 #for sgd optim
amsgrad: 1 #for adam optim
make_label_dic: 1

#model-related
model:
  first_conv: 12
  in_channels: 2
  filts: [128, [128, 64, 64], [64, 128,128], [128, 128,128], 128]
  nb_fc_node: 128
  nb_classes: 10
